In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-08-25 11:05:11.443551: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5222, 537, 2105, 4235],
 [5222, 537, 2105, 6856],
 [5222, 2804, 2105, 1816],
 [1379, 8605, 2233, 1195, 9409],
 [1379, 8605, 2233, 1195, 8175],
 [6049, 5222, 8756, 2105, 2728],
 [6489, 1736, 6542, 1195]]

In [10]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [15]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
voc_size=10000
one_hot_repr=[one_hot(words,voc_size)for words in sent]
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5222  537 2105 4235]
 [   0    0    0    0 5222  537 2105 6856]
 [   0    0    0    0 5222 2804 2105 1816]
 [   0    0    0 1379 8605 2233 1195 9409]
 [   0    0    0 1379 8605 2233 1195 8175]
 [   0    0    0 6049 5222 8756 2105 2728]
 [   0    0    0    0 6489 1736 6542 1195]]


In [16]:
## feature representation
dim = 10

### Create model for Embedding Layer

### Here Embedding from keras internally uses word2vec to convert your words to a vector with feature dimension of dim.

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

# Define the model
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Print the model summary
model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[[ 3.6695171e-02, -6.7288801e-04, -3.6572017e-02, -1.4934897e-02,
          4.3631267e-02,  2.3945596e-02,  3.1528879e-02,  2.5925387e-02,
          1.4953624e-02,  2.2370998e-02],
        [ 3.6695171e-02, -6.7288801e-04, -3.6572017e-02, -1.4934897e-02,
          4.3631267e-02,  2.3945596e-02,  3.1528879e-02,  2.5925387e-02,
          1.4953624e-02,  2.2370998e-02],
        [ 3.6695171e-02, -6.7288801e-04, -3.6572017e-02, -1.4934897e-02,
          4.3631267e-02,  2.3945596e-02,  3.1528879e-02,  2.5925387e-02,
          1.4953624e-02,  2.2370998e-02],
        [ 3.6695171e-02, -6.7288801e-04, -3.6572017e-02, -1.4934897e-02,
          4.3631267e-02,  2.3945596e-02,  3.1528879e-02,  2.5925387e-02,
          1.4953624e-02,  2.2370998e-02],
        [ 3.4045961e-02, -1.6851507e-02, -2.0492792e-02, -4.4766843e-02,
          3.9200116e-02, -4.3071449e-02, -4.2804051e-02,  2.1803681e-02,
          8.4058419e-03,  6.3904524e-03],
        [ 4.6768550e-02,  4.2669181e-02, -4.8815835e-02, -1.

In [41]:
embedded_docs

array([[   0,    0,    0,    0, 5222,  537, 2105, 4235],
       [   0,    0,    0,    0, 5222,  537, 2105, 6856],
       [   0,    0,    0,    0, 5222, 2804, 2105, 1816],
       [   0,    0,    0, 1379, 8605, 2233, 1195, 9409],
       [   0,    0,    0, 1379, 8605, 2233, 1195, 8175],
       [   0,    0,    0, 6049, 5222, 8756, 2105, 2728],
       [   0,    0,    0,    0, 6489, 1736, 6542, 1195]], dtype=int32)

In [30]:
te = [
    [0, 0, 0, 0, 5222, 537, 2105, 4235],
    [0, 0, 0, 0, 5222, 537, 2105, 6856],
    [0, 0, 0, 0, 5222, 2804, 2105, 1816],
    [0, 0, 0, 1379, 8605, 2233, 1195, 9409],
    [0, 0, 0, 1379, 8605, 2233, 1195, 8175],
    [0, 0, 0, 6049, 5222, 8756, 2105, 2728],
    [0, 0, 0, 0, 6489, 1736, 6542, 1195]
]

In [31]:
len(te)

7

In [32]:
te[0]

[0, 0, 0, 0, 5222, 537, 2105, 4235]

In [27]:
len(embedded_docs)

7

In [36]:
len(embedded_docs[0])

8

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 5222,  537, 2105, 4235], dtype=int32)

In [34]:
model.predict(te[0], dtype=int32)

NameError: name 'int32' is not defined

In [35]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [42]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

#### It looks like the issue is related to the shape of the input tensor. The error “Cannot take the length of shape with unknown rank” suggests that the model is not receiving the input in the expected format. To resolve this, you need to ensure that the input to model.predict has the correct shape. Specifically, the input should have a batch dimension, even if it’s just a single sequence. Here’s how you can modify your code:

# Let's try this

In [43]:
model.predict(np.array(embedded_docs[0]))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

## Okay so that didn't work either!!

In [46]:
type(embedded_docs)

numpy.ndarray

In [48]:
embedded_docs[0].shape

(8,)

In [49]:
np.array([embedded_docs[0]]).shape

(1, 8)

## So it needs data in (batch_size, sent_length) format!

```
Expected Shape:
The model expects the input to have a shape of (batch_size, sent_length). This means:

batch_size: The number of sequences you are passing to the model at once. Even if it’s just one sequence, it should be wrapped in an array to create a batch of size 1.
sent_length: The length of each sequence (in your case, 8).
What You Were Passing:
When you passed embedded_docs[0], you were passing a single sequence with shape (8,). This does not include the batch dimension, which is why the model raised an error.

Correct Shape:
To avoid the error, you need to wrap the single sequence in an array to create a batch of size 1. This changes the shape from (8,) to (1, 8).
```

# Correct way:

In [50]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[[ 0.03669517, -0.00067289, -0.03657202, -0.0149349 ,
          0.04363127,  0.0239456 ,  0.03152888,  0.02592539,
          0.01495362,  0.022371  ],
        [ 0.03669517, -0.00067289, -0.03657202, -0.0149349 ,
          0.04363127,  0.0239456 ,  0.03152888,  0.02592539,
          0.01495362,  0.022371  ],
        [ 0.03669517, -0.00067289, -0.03657202, -0.0149349 ,
          0.04363127,  0.0239456 ,  0.03152888,  0.02592539,
          0.01495362,  0.022371  ],
        [ 0.03669517, -0.00067289, -0.03657202, -0.0149349 ,
          0.04363127,  0.0239456 ,  0.03152888,  0.02592539,
          0.01495362,  0.022371  ],
        [ 0.03404596, -0.01685151, -0.02049279, -0.04476684,
          0.03920012, -0.04307145, -0.04280405,  0.02180368,
          0.00840584,  0.00639045],
        [ 0.04676855,  0.04266918, -0.04881584, -0.01976486,
         -0.04986755,  0.02827475, -0.01023549, -0.04924753,
          0.0136219 ,  0.02512655],
        [-0.03847091,  0.0001027 , -0.00229814, -0.0

## So here you go, This is power of word embedding! You can see first sentence has 8 words and each word is represented by a vector of 10 features